### PR TITLE
Adding argparse

### PR DESCRIPTION
**Pull request by erinyoung**
I don't want to step on any toes!

I have finally looked at HeatCluster.py. I wanted to contribute some suggestions, so I created a fork, added some test files, and then adjusted HeatCluster.py so that these files would work.

Notable changes:
- Added argparse for additional functionality of input and output file names and extensions
- I added several files for some common options given to snp-dists including `-m` ([melted.txt](https://github.com/erinyoung/HeatCluster/blob/main/test/melted.txt)) and `-b` ([blank.txt](https://github.com/erinyoung/HeatCluster/blob/main/test/blank.txt)). Right now the script doesn't supported melted inputs, but there is now a test file so that incorporating it would be easier in the figure.
- I added text to the readme. This was done very quickly, so I apologize for all errors and missing information.
- I also incremented the version

I have run into an issue with large SNP matrices (see attached), which I didn't have time to resolve.
[larget.pdf](https://github.com/DrB-S/HeatCluster/files/12423649/larget.pdf)

### CODE REVIEW

**Comment by DrB-S** [comment]
Thanks for your updates! I am checking them out. I like the way you automated the figure size. To make it fit better for large matrices, I also changed the font size with "sns.set(font_scale=0.25)". I am looking into how you were able to get the reordered matrix to appear that way in the pdf & png heatmaps at the moment.

**Review by DrB-S — APPROVED** [review]
Great additions! I approve these changes. 
I am working on adding modifications that handle larger matrices:
1. Reducing font size when there are more than 120 samples:
   if (numSamples >120):
        sns.set(font_scale=0.25)
2. Faster manipulations of the matrix using polars

**Comment by DrB-S** [comment]
Do you know how to pass arguments to python scripts when running them in the interactive window of VS Code?

**Comment by erinyoung** [comment]
I think you can just give them arguments values when running them interactively

**Comment by DrB-S** [comment]
I don't see an obvious way to do that in VS Code. I can run the script in a terminal window within VS Code and add the arguments. But the only way to actually display the output images requires running in the interactive window, which doesn't give an option to add arguments.

**Comment by erinyoung** [comment]
If you're using debugging mode, you should be able to put your values into launch.json (more information here https://code.visualstudio.com/docs/python/debugging)

**Pull request merged**
