### PR TITLE
reverted back to logging

### PR DESCRIPTION
**Pull request by erinyoung**
I've added logging back in. It looks like you've been making more of your changes on your "main" branch, which are a little harder to track. If you create a branch to make your changes in, then you can create pull requests, which should trigger the GA so that you can be sure you aren't breaking anything as you update.

logging is not "required" by pypi, but it is highly recommended. Most versions of python3 already have logging installed, but if you find an environment without use `pip install logging` to get it installed in your working environment.

### CODE REVIEW

**Review by DrB-S — APPROVED** [review]
Thanks! Looks good.

**Review by DrB-S — APPROVED** [review]
Why scipy? I don't see it anywhere in the code.

**Comment by erinyoung** [comment]
I think it was there in older files? A lot of your edits were to your "main" branch, and I had difficulties tracking down where the errors were.

**Review by DrB-S — CHANGES_REQUESTED** [review]
It looks great with the exception of the saved figure (heatmap.savefig). "SNP_matrix.pdf" is fine as the default, but when the "-o" argument is used with a different name, that name should be used.

**Pull request closed without merging**
